### ISSUE TITLE
Property descriptions are not correctly parsed

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-signalfx#377] opened 2024-01-23 00:16 UTC
### What happened?

https://github.com/pulumi/pulumi-signalfx/pull/376 moved all field descriptions from properties to the resource itself

### Example

For example, see the description of `log.Timeline`:

https://github.com/pulumi/pulumi-signalfx/blob/a77ffa695341dd87e60238aa8244462dfafd96d3/sdk/go/signalfx/log/timeline.go#L21-L38

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment] 2024-05-10 20:58
Yeah. This was caused by https://github.com/splunk-terraform/terraform-provider-signalfx/commit/1d546af42678ed448e16ae7000bacd0d485134f6#diff-5d8d1f8003f2c9dfb27fb6bf79f93810608bad998263250a34164a638ab6a170. 

Specifically

Example Usage => Example
Argument Reference => Arguments
Attributes Reference => Attributes

Looking into what our options are here. 🤞

**Comment by guineveresaenger** [comment] 2024-05-13 16:12
Closed via https://github.com/pulumi/pulumi-terraform-bridge/pull/1959

**Closed by guineveresaenger** 2024-05-13 16:12 UTC
Labels: resolution/fixed, kind/bug, area/docs
